INSERT INTO category (category_name) VALUES ('American');
INSERT INTO category (category_name) VALUES ('Italian');
INSERT INTO category (category_name) VALUES ('Mexican');
INSERT INTO category (category_name) VALUES ('Japanese');
INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Cup');
INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Pinch');
INSERT INTO unit_of_measure (unit_of_measure) VALUES ('Ounce');